### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ScreNN** [traefik-plugins/traefikgeoip2#2] opened 2023-06-07 14:54 UTC
It looks like the plugin is no longer supported?

`level=error msg="Plugins are disabled because an error has occurred." error="failed to check archive integrity of the plugin github.com/GiGInnovationLabs/traefikgeoip2: plugin integrity check failed"`

**Comment by ievgenii-shepeliuk** [comment] 2023-06-12 07:40
Duplicate of #1

**Closed as completed by ievgenii-shepeliuk** 2023-06-12 07:40 UTC
